"""initial schema

Revision ID: 94c2d3062de4
Revises:
Create Date: 2026-09-04 10:32:36.042243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94c2d3062de4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "uq_admin_users_single_active",
        "admin_users",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "encrypted_secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("secret_type", sa.String(length=64), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_admin_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("before_snapshot", postgresql.JSONB(), nullable=True),
        sa.Column("after_snapshot", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_admin_user_id"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_entity", "audit_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "telegram_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("identity_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("secret_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "health_status IN ('unknown', 'healthy', 'degraded', 'failed')",
            name="ck_telegram_identity_health",
        ),
        sa.CheckConstraint(
            "identity_type IN ('mtproto_user', 'bot')", name="ck_telegram_identity_type"
        ),
        sa.ForeignKeyConstraint(["secret_id"], ["encrypted_secrets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "destination_channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_identity_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_identity_id"], ["telegram_identities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "telegram_identity_id",
            "telegram_channel_id",
            name="uq_destination_channel_identity_remote",
        ),
    )
    op.create_table(
        "source_channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_identity_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_identity_id"], ["telegram_identities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "telegram_identity_id", "telegram_channel_id", name="uq_source_channel_identity_remote"
        ),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_channel_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_anchor_message_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_group_id", sa.BigInteger(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("visual_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("source_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_changed_after_processing", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_channel_id"], ["source_channels.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_channel_id", "telegram_anchor_message_id", name="uq_message_source_anchor"
        ),
    )
    op.create_index(
        "ix_messages_source_sent_at", "messages", ["source_channel_id", "sent_at"], unique=False
    )
    op.create_table(
        "source_channel_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_channel_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_channel_id"], ["source_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_channel_id"),
    )
    op.create_table(
        "source_channel_profile_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("content", postgresql.JSONB(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('draft', 'published', 'retired')", name="ck_source_profile_version_state"
        ),
        sa.CheckConstraint(
            "(state = 'draft' AND published_at IS NULL) "
            "OR (state IN ('published', 'retired') AND published_at IS NOT NULL)",
            name="ck_source_profile_version_published_at",
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["source_channel_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "content_hash", name="uq_source_profile_content_hash"),
        sa.UniqueConstraint(
            "profile_id", "version_number", name="uq_source_profile_version_number"
        ),
    )
    op.execute(
        """
        CREATE FUNCTION tgcurator_enforce_source_profile_version_immutability()
        RETURNS trigger
        AS $$
        BEGIN
            IF OLD.state = 'retired' THEN
                RAISE EXCEPTION 'retired source profile versions are immutable';
            END IF;
            IF OLD.state = 'published' AND (
                NEW.profile_id IS DISTINCT FROM OLD.profile_id
                OR NEW.version_number IS DISTINCT FROM OLD.version_number
                OR NEW.content IS DISTINCT FROM OLD.content
                OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
                OR NEW.published_at IS DISTINCT FROM OLD.published_at
                OR NEW.state NOT IN ('published', 'retired')
            ) THEN
                RAISE EXCEPTION 'published source profile version content is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_source_profile_version_immutable "
        "BEFORE UPDATE ON source_channel_profile_versions "
        "FOR EACH ROW EXECUTE FUNCTION tgcurator_enforce_source_profile_version_immutability()"
    )
    op.create_table(
        "processing_ranges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_channel_id", sa.Uuid(), nullable=False),
        sa.Column("source_profile_version_id", sa.Uuid(), nullable=False),
        sa.Column("boundary_kind", sa.String(length=16), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fixed_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_quiet_seconds", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(boundary_kind = 'fixed' "
            "AND fixed_end_at IS NOT NULL "
            "AND latest_quiet_seconds IS NULL) "
            "OR (boundary_kind = 'latest' "
            "AND fixed_end_at IS NULL "
            "AND latest_quiet_seconds IS NOT NULL)",
            name="ck_processing_range_boundary_fields",
        ),
        sa.CheckConstraint(
            "boundary_kind IN ('fixed', 'latest')", name="ck_processing_range_boundary_kind"
        ),
        sa.CheckConstraint(
            "fixed_end_at IS NULL OR fixed_end_at > start_at",
            name="ck_processing_range_fixed_order",
        ),
        sa.CheckConstraint(
            "latest_quiet_seconds IS NULL OR latest_quiet_seconds > 0",
            name="ck_processing_range_quiet_positive",
        ),
        sa.ForeignKeyConstraint(["source_channel_id"], ["source_channels.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_profile_version_id"],
            ["source_channel_profile_versions.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processing_ranges")
    op.execute(
        "DROP TRIGGER trg_source_profile_version_immutable ON source_channel_profile_versions"
    )
    op.execute("DROP FUNCTION tgcurator_enforce_source_profile_version_immutability()")
    op.drop_table("source_channel_profile_versions")
    op.drop_table("source_channel_profiles")
    op.drop_index("ix_messages_source_sent_at", table_name="messages")
    op.drop_table("messages")
    op.drop_table("source_channels")
    op.drop_table("destination_channels")
    op.drop_table("telegram_identities")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("encrypted_secrets")
    op.drop_index("uq_admin_users_single_active", table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
